# This workflow is to mark stale issues

name: Assign Stale issues to myself

on:
    schedule:
        - cron: 0 0 * * *

jobs:
    
    issue_tracker:
        runs-on: ubuntu-latest
        steps:
            - name: Make issue Stale
              uses: actions/stale@v9.1.0
              with:
                days-before-stale: 30
                stale-issue-label: Stale                